package br.com.i9algo.taxiadv.domain.enums;

public enum ActionsEnum {
	ACTION_PLAYLIST_MINIMIZE, 
	ACTION_PLAYLIST_MAXIMIZE, 
	ACTION_PLAYLIST_PAUSE,
	ACTION_PLAYLIST_PLAY,
	ACTION_PLAYLIST_NEXT, // Proximo item da playlist
	//ACTION_PLAYLIST_PREV, // Item anterior da playlist
	ACTION_POWER_CONNECTED, 
	ACTION_POWER_DISCONNECTED,
	ACTION_TIMER_INIT,
	ACTION_TIMER_STOP,
	STARTED_DEVICE, 
	STARTED_APPLICATION, 
	LOW_BATTERY,
	INITIALIZE_NAVIGATION_BUTTONS;
}
